server:
  port: 9600

spring:
  application:
    name: h2-demo

  datasource:
    driver-class-name: org.h2.Driver
    # h2 内存数据库 内存模式连接配置 库名: spring_security mysql模式
    url: jdbc:h2:mem:h2_demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=MYSQL
    username: admin
    password: 123456

  h2:
    console:
      # h2 数据库开启页面访问 http://localhost:9600/h2-console
      path: /h2-console
      # 开启console 访问 默认false
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试 默认 false
        trace: true
        # 允许console 远程访问 默认false
        web-allow-others: true
  sql:
    init:
      # 初始化数据表 DDL
      schema-locations: classpath:sql/ddl.sql
      # 初始化数据 DML
      data-locations: classpath:sql/dml.sql
      mode: embedded

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:**/mapper/xml/*.xml


